import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-provisioning-secret, x-client-info, apikey, content-type",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  try {
    // ── 1. Auth: verify caller using S2S secret ────────────────────────
    const secretHeader = req.headers.get("x-provisioning-secret");
    const expectedSecret = Deno.env.get("PROVISIONING_SECRET");
    
    if (!secretHeader || !expectedSecret || secretHeader !== expectedSecret) {
      return Response.json({ error: "Unauthorized" }, { status: 401, headers: corsHeaders });
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
    const serviceRoleKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const serviceClient = createClient(supabaseUrl, serviceRoleKey);

    // ── 2. Parse + validate body ───────────────────────────────────────
    const body = await req.json();
    const { idempotencyKey, school, admin, subscription } = body;

    if (!idempotencyKey) {
      return Response.json({ error: "idempotencyKey is required" }, { status: 400, headers: corsHeaders });
    }
    
    if (!school?.name || !school?.code) {
      return Response.json({ error: "school name and code are required" }, { status: 400, headers: corsHeaders });
    }

    // ── 3. Idempotency Check ──────────────────────────────────────────
    const { data: existingRequest, error: checkError } = await serviceClient
      .from("provisioning_requests")
      .select("*")
      .eq("idempotency_key", idempotencyKey)
      .maybeSingle();

    if (checkError) throw checkError;

    if (existingRequest) {
      return Response.json(
        { 
          success: true, 
          data: {
            schoolId: existingRequest.school_id,
            tenantId: existingRequest.tenant_id,
            message: "School already provisioned (idempotent)"
          }
        },
        { status: 200, headers: corsHeaders }
      );
    }

    // ── 4. CREATE tenant ──────────────────────────────────────────────
    const randomPin = "SCH-" + Array.from({length: 6}, () => Math.random().toString(36).charAt(2)).join('').toUpperCase();
    
    const { data: newTenantId, error: tenantError } = await serviceClient.rpc("create_tenant_v2", {
      _school_name: school.name,
      _school_pin: randomPin,
      _contact_email: school.email || null,
      _contact_phone: school.phone || null,
      _notes: null,
      _start_trial: true,
    });
    
    if (tenantError) throw tenantError;
    const actualTenantId = newTenantId;

    // ── 5. INSERT school ──────────────────────────────────────────────
    let maxStudentsLimit = 500;
    if (subscription?.plan === "pro") maxStudentsLimit = 2000;
    if (subscription?.plan === "enterprise") maxStudentsLimit = 10000;

    const { data: newSchool, error: schoolError } = await serviceClient
      .from("schools")
      .insert({
        tenant_id: actualTenantId,
        name: school.name,
        code: school.code.toUpperCase(),
        email: school.email ?? null,
        phone: school.phone ?? null,
        address_street: school.address?.street ?? null,
        address_city: school.address?.city ?? null,
        address_state: school.address?.state ?? null,
        max_students: maxStudentsLimit,
      })
      .select("id")
      .single();

    if (schoolError) {
      if (schoolError.code === "23505") { // Unique violation
        return Response.json({ error: { code: "school_code_conflict", message: "School code already exists" } }, { status: 409, headers: corsHeaders });
      }
      throw schoolError;
    }

    const schoolId = newSchool.id;

    // ── 6. CREATE Admin User (replaces pre_registrations) ──────────────
    if (admin?.email && admin?.tempPassword) {
      const { data: authData, error: authError } = await serviceClient.auth.admin.createUser({
        email: admin.email.toLowerCase(),
        password: admin.tempPassword,
        email_confirm: true,
        user_metadata: {
          full_name: admin.name,
          school_id: schoolId,
          must_reset_password: true,
        }
      });

      if (authError) throw authError;

      // Update the profile that was auto-generated by handle_new_user_profile trigger
      const { error: profileError } = await serviceClient
        .from("profiles")
        .update({
          school_id: actualTenantId,
          role: "school_admin",
          first_name: admin.name?.split(' ')[0] || null,
          last_name: admin.name?.split(' ').slice(1).join(' ') || null,
        })
        .eq("id", authData.user.id);
        
      if (profileError) throw profileError;
    }

    // ── 7. INSERT billing record ──────────────────────────────────────
    const trialEndsAt = subscription?.trialEndsAt || new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString();
    const { error: billingError } = await serviceClient
      .from("billing")
      .insert({
        school_id: schoolId,
        plan: subscription?.plan ?? "starter",
        status: "trial",
        trial_ends_at: trialEndsAt,
        payment_method: subscription?.paymentMethod ?? null,
      });

    if (billingError) throw billingError;

    // ── 8. Log Idempotency ─────────────────────────────────────────────
    const { error: idemError } = await serviceClient
      .from("provisioning_requests")
      .insert({
        idempotency_key: idempotencyKey,
        tenant_id: actualTenantId,
        school_id: schoolId,
      });

    if (idemError) throw idemError;

    // (Note: Email sending is now handled completely by titbeattech-nextjs)

    return Response.json(
      { 
        success: true, 
        data: { 
          schoolId,
          tenantId: actualTenantId,
          message: "School successfully provisioned"
        } 
      },
      { status: 201, headers: corsHeaders }
    );
  } catch (err) {
    console.error("provision-school error:", err);
    return Response.json(
      { error: err instanceof Error ? err.message : "Internal server error" },
      { status: 500, headers: corsHeaders }
    );
  }
});
